[book]
authors = ["Jordan Hollinger"]
language = "en"
multilingual = false
src = "src"
title = "Occams Record"

[build]
build-dir = "docs"

# https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=top%20bar#html-renderer-options
[output.html]
git-repository-url = "https://github.com/jhollinger/occams-record"
