name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test-current:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.2", "3.3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          bundle exec appraisal install --path=vendor/bundle
      - name: Run tests
        run: bundle exec appraisal rake test

  test-3_1:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          bundle exec appraisal ar-6.1 bundle install --path=vendor/bundle
          bundle exec appraisal ar-7.0 bundle install --path=vendor/bundle
          bundle exec appraisal ar-7.1 bundle install --path=vendor/bundle
          bundle exec appraisal ar-7.2 bundle install --path=vendor/bundle
      - name: Run tests
        run: |
          bundle exec appraisal ar-6.1 rake test
          bundle exec appraisal ar-7.0 rake test
          bundle exec appraisal ar-7.1 rake test
          bundle exec appraisal ar-7.2 rake test
