name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test-current:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby:
          - "4.0"
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: |
          cp Appraisals.ruby-${{ matrix.ruby }} Appraisals
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          bundle exec appraisal install --path=vendor/bundle
      - name: Run tests
        run: bundle exec appraisal rake test
